### ISSUE TITLE
Bone Compression Crash

### ISSUE THREAD

**Issue by MadMax1960** [WistfulHopes/SparkingZERO_ModProject#1]
Insta crashes with error Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Animation\AnimationUtils.cpp] [Line: 901] Couldn't load default compression settings asset with path '/ACLPlugin/ACLAnimBoneCompressionSettings'

**Comment by WistfulHopes** [comment]
fixed
